# SPDX-FileCopyrightText: 2026 Quentin Cazier <cazierquentin@gmail.com>
#
# SPDX-License-Identifier: MIT

# Forward secure sealing of the journal. The keys are generated by the
# installer, see lib/default.nix.
{ config, lib, ... }:
let
  cfg = config.securix.journaldFSS;
  inherit (lib) mkEnableOption mkIf;
in
{
  options.securix.journaldFSS = {
    enable = mkEnableOption "forward secure sealing of the system journal";
  };

  config = mkIf cfg.enable {
    services.journald.extraConfig = ''
      Storage=persistent
      Seal=yes
    '';
  };
}
