final: prev: {
  # We patch the speakeasy dependency because we need
  # https://github.com/bgentry/speakeasy/issues/22
  openbao = prev.openbao.overrideModAttrs (_: {
    # These checksums can be generated by
    # go get github.com/bgentry/speakeasy@v0.2.0
    # go mod tidy
    postPatch = ''
      sed -i 's|github.com/bgentry/speakeasy v0.1.0|github.com/bgentry/speakeasy v0.2.0|' go.mod
      sed -i 's|github.com/bgentry/speakeasy v0.1.0 h1:ByYyxL9InA1OWqxJqqp2A5pYHUrCiAL6K3J+LKSsQkY=|github.com/bgentry/speakeasy v0.2.0 h1:tgObeVOf8WAvtuAX6DhJ4xks4CFNwPDZiqzGqIHE51E=|' go.sum
      sed -i 's|github.com/bgentry/speakeasy v0.1.0/go.mod h1:+zsyZBPWlz7T6j88CTgSN5bM796AkVf0kBD4zp0CCIs=|github.com/bgentry/speakeasy v0.2.0/go.mod h1:+zsyZBPWlz7T6j88CTgSN5bM796AkVf0kBD4zp0CCIs=|' go.sum
    '';
  });
}
