# SPDX-FileCopyrightText: 2025 Julien DAUPHANT <julien.dauphant@numerique.gouv.fr>
#
# SPDX-License-Identifier: MIT

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  inherit (lib) mkIf;
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  config = mkIf (config.securix.self.hardwareSKU == "t14g6") {
    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "usb_storage"
      "sd_mod"
      "thunderbolt"
    ];
    boot.initrd.kernelModules = [ "xe" ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.kernelParams = [
      "acpi_backlight=native"
      "psmouse.synaptics_intertouch=0"
    ];
    boot.extraModulePackages = [ ];

    hardware.firmware = [
      # WiFi
      pkgs.linux-firmware
      pkgs.wireless-regdb
    ];

    hardware.graphics.extraPackages = [
      pkgs.intel-media-driver
      pkgs.intel-compute-runtime
      pkgs.vpl-gpu-rt
    ];

    hardware.trackpoint.enable = lib.mkDefault true;
    hardware.trackpoint.emulateWheel = lib.mkDefault config.hardware.trackpoint.enable;
    services.fstrim.enable = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    services.throttled.enable = lib.mkDefault false;
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
